### PR TITLE
Integrate tblite library for evaluating xTB Hamiltonians

### LINKED ISSUE #514: Integration of tblite library
*This is a tracking issue to integrate the [tblite] library with `xtb`.*

To get the PBC support in `xtb` finally in a usable state we have to integrate the [tblite] library which started as a spin off to support the xTB methods in DFTB+.

This will enable:

- customizable and programmatically accessible parameter files (breaking change in the parameter format, again)
- periodic boundary condition support for GFN1-xTB and GFN2-xTB

Things to take care of first:

- integration of solvation models, here in `xtb` or in library?
  https://github.com/tblite/tblite/issues/23
- external potentials, defined by `xtb` or in library?
  https://github.com/tblite/tblite/issues/22
- support for GFN0-xTB in library?
  https://github.com/tblite/tblite/issues/29

[tblite]: https://github.com/awvwgk/tblite

### PR DESCRIPTION
**Pull request by awvwgk**
- [x] enable optional build with [tblite](https://tblite.readthedocs.io)
     - [x] support as feature in meson (default: auto-detect)
     - [x] support as option CMake (default: off?)
- [x] provide calculator implementation
     - [x] basic single point calculator
     - [x] allow selection of method or parameter file
     - ~~allow creation of solvation models~~ (separate PR)
     - ~~provide info printout from parametrization~~ (separate PR)
- [x] regression tests
- [x] documentation about new option

Closes #514

### CODE REVIEW

**Comment by awvwgk** [comment]
This is mostly complete, in case anyone is interested in helping to get it merged let me know.

**Comment by awvwgk** [comment]
Ready for review.

**Comment by awvwgk** [comment]
Yes, that is due to libraries without direct OpenMP dependency in the tree

**Linux**
```
meson setup _build \
        -Dprefix=/ \
        -Dlibdir=lib \
        -Dbuildtype=release \
        -Dfortran_link_args="-lifcoremt -static" \
        -Ddefault_library=static \
        -Dlapack=mkl
meson compiler -C _build
meson install -C _build --destdir $PWD/xtb-dist
```

**Windows (powershell)**
```
meson setup _build `
    -Dfortran_args="/fpp" `
    -Ddefault_library=static `
    -Db_vscrt=mt `
    -Dbuildtype=release `
    -Dla_backend=custom `
    -Dfortran_link_args="mkl_intel_lp64.lib mkl_intel_thread.lib mkl_core.lib libiomp5md.lib ifcoremt.lib /STACK:16777216"
meson compile -C _build
meson install -C _build --destdir $pwd\xtb-dist
cp $env:MKLROOT\..\..\compiler\latest\windows\redist\intel64_win\compiler\libiomp5md.dll xtb-dist\bin
```

Might work to just drop-in `-Dfortran_args=-qopenmp` / `-Dfortran_args=/qopenmp` instead of messing with the link arguments.

**Comment by MtoLStoN** [comment]
Agree. As stated, adding an explicit -lifcoremt linker flag works for me for static linking. However, the dynamic build needs an additional "-qopenmp" linker flag to compile, which is nothing terrible, but we should probably include that in the README to prevent future questions.

Otherwise, this looks good to me.

**Review by MtoLStoN — APPROVED** [review]

**Review by cplett — APPROVED** [review]

**Comment by MtoLStoN** [comment]
Thanks for sharing.

**Pull request merged**
