### PR TITLE
enables dynamic linking

### LINKED ISSUE #12: Compiling xtb on OSX
*updated and edited*
Compiling on OSX might interest a few people. 

A few hurdles I ran into:
* needs a fully 'shared' build option as static linking is not really a thing on OSX
* requires at least: `meson configure -Db_lundef=false` (possibly also for gcc)

---

current working version on Catalina and Intel19
grab: https://github.com/hokru/xtb/tree/osx3 (shortened meson config plus PR #40)

```
export FC=ifort CC=icc CXX=icpc
meson setup build_intel -Dstatic=false -Db_lundef=false -Db_asneeded=false
```
There will be an error because of wrong linking flags! Ignore and link yourself:
```
ifort  -o xtb 'xtb@exe/xtb_program_main.f90.o' -qopenmp -mkl libxtb.a  -Wl,-rpath,/INSERT_YOUR_PATH/xtb/build_intel/ libxtb.dylib
```

### PR DESCRIPTION
**Pull request by awvwgk**
should fix #12, #39

requires meson 0.51

### CODE REVIEW

**Comment by xiki-tempula** [comment]
I have tried to compile this PR on our cluster but encountered this error.

```
[278/280] Linking target xtb_test.
FAILED: xtb_test 
ifort  -o xtb_test 'xtb_test@exe/TESTSUITE_tests_peeq.f90.o' 'xtb_test@exe/TESTSUITE_assertion.f90.o' 'xtb_test@exe/TESTSUITE_tbdef_molecule.f90.o' 'xtb_test@exe/TESTSUITE_tbdef_wsc.f90.o' 'xtb_test@exe/TESTSUITE_geometry_reader.f90.o' 'xtb_test@exe/TESTSUITE_eeq_model.f90.o' 'xtb_test@exe/TESTSUITE_pbc_tools.f90.o' 'xtb_test@exe/TESTSUITE_dftd4.f90.o' 'xtb_test@exe/TESTSUITE_gfn2.f90.o' 'xtb_test@exe/TESTSUITE_gfn1.f90.o' 'xtb_test@exe/TESTSUITE_gfn0.f90.o' 'xtb_test@exe/TESTSUITE_peeq.f90.o' 'xtb_test@exe/TESTSUITE_symmetry.f90.o' 'xtb_test@exe/TESTSUITE_thermo.f90.o' 'xtb_test@exe/TESTSUITE_tbdef_atomlist.f90.o' -Wl,--as-needed -Wl,--no-undefined -static -qopenmp -Wl,--start-group libxtb.a -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -Wl,--end-group -pthread '-Wl,-rpath,$ORIGIN/' -Wl,-rpath-link,/users/grte2001/src/xtb-6.2.1/build_intel/
ifort: command line warning #10418: option -reentrancy=threaded requires pthread library which cannot be statically linked.  Reverting to -reentrancy=none
ld: cannot find -lm
[279/280] Linking target xtb.
FAILED: xtb 
ifort  -o xtb 'xtb@exe/xtb_program_main.f90.o' -Wl,--as-needed -Wl,--no-undefined -static -qopenmp -Wl,--start-group libxtb.a -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -Wl,--end-group -pthread '-Wl,-rpath,$ORIGIN/' -Wl,-rpath-link,/users/grte2001/src/xtb-6.2.1/build_intel/
ifort: command line warning #10418: option -reentrancy=threaded requires pthread library which cannot be statically linked.  Reverting to -reentrancy=none
ld: cannot find -lm
ninja: build stopped: subcommand failed.
```

I wonder if there is any way of resolving this problem? Thank you.

**Comment by awvwgk** [comment]
This PR just enables dynamic linking, it does not replace the default behaviour. Use

```bash
meson setup build_intel -Dstatic=false
```

**Comment by pierre-24** [comment]
Hey, since #49 is merged, should I test again this PR?

**Comment by awvwgk** [comment]
@pierre-24 it has been rebased against #49, so give it a try.

**Comment by pierre-24** [comment]
This time it is working :)

```
[279/280] Running all tests.
 1/61 Argparser: print version                OK       0.03 s 
 2/61 Argparser: print help                   OK       0.04 s 
 3/61 Argparser: print license                OK       0.05 s 
 4/61 Argparser: no arguments                 EXPECTEDFAIL 0.05 s 
 5/61 Runtyp: singlepoint                     OK       1.15 s 
 6/61 Runtyp: geometry opt.                   OK       2.20 s 
 7/61 Runtyp: IP/EA                           OK       1.98 s 
 8/61 Method: GFN0-xTB                        OK       0.52 s 
 9/61 Method: GFN1-xTB                        OK       0.96 s 
10/61 Method: GFN2-xTB/GBSA                   OK       1.50 s 
11/61 Molecule Class: axis                    OK       0.23 s 
12/61 Molecule Class: MIC                     OK       0.11 s 
13/61 Wigner-Seitz Cell (0D)                  OK       0.18 s 
14/61 Wigner-Seitz Cell (3D)                  OK       0.24 s 
15/61 Geometry Reader: coord 3D               OK       0.05 s 
16/61 Geometry Reader: coord 3D               OK       0.15 s 
17/61 Geometry Reader: coord 2D               SKIP     0.25 s 
18/61 Geometry Reader: coord 1D               SKIP     0.13 s 
19/61 Geometry Reader: coord 0D               OK       0.13 s 
20/61 Geometry Reader: Xmol  0D               OK       0.24 s 
21/61 Geometry Reader: POSCAR                 OK       0.19 s 
22/61 Geometry Reader: molfile                OK       0.08 s 
23/61 Geometry Reader: molfile flat           EXPECTEDFAIL 0.14 s 
24/61 Geometry Reader: SDF                    OK       0.08 s 
25/61 Geometry Reader: SDF flat               EXPECTEDFAIL 0.02 s 
26/61 Geometry Reader: SDF no H               EXPECTEDFAIL 0.04 s 
27/61 Geometry Reader: PDB                    OK       0.15 s 
28/61 Geometry Reader: PDB no H               EXPECTEDFAIL 0.12 s 
29/61 IO: atom list                           OK       0.10 s 
30/61 PBC tools: convert                      OK       0.07 s 
31/61 PBC tools: cutoff                       OK       0.12 s 
32/61 Symmetry: Water                         OK       0.17 s 
33/61 Symmetry: Li8                           OK       0.11 s 
34/61 Symmetry: PCl3                          OK       0.13 s 
35/61 Symmetry: large                         OK       0.84 s 
36/61 Thermo: axis                            OK       0.48 s 
37/61 Thermo: calculation                     OK       0.10 s 
38/61 Thermo: print                           OK       0.10 s 
39/61 EEQ model: water                        OK       0.64 s 
40/61 EEQ model: 3D Ewald                     OK       0.69 s 
41/61 EEQ model: GBSA                         OK       0.68 s 
42/61 EEQ model: GBSA (salt)                  OK       0.57 s 
43/61 EEQ model: GBSA (H-bond)                SKIP     0.06 s 
44/61 Dispersion: properties                  OK       0.08 s 
45/61 Dispersion: energies                    OK       0.45 s 
46/61 Dispersion: energies (PBC)              OK       2.52 s 
47/61 Dispersion: API                         OK       0.47 s 
48/61 GFN2-xTB: SCC                           OK       0.57 s 
49/61 GFN2-xTB: API                           OK       0.32 s 
50/61 GFN2-xTB: API (GBSA)                    OK       1.07 s 
51/61 GFN2-xTB: API (GBSA+salt)               OK       0.99 s 
52/61 GFN2-xTB: API (PCEM)                    OK       0.85 s 
53/61 GFN2-xTB: C++                           OK       0.57 s 
54/61 GFN1-xTB: SCC                           OK       0.65 s 
55/61 GFN1-xTB: API                           OK       0.83 s 
56/61 GFN1-xTB: API (GBSA)                    OK       0.78 s 
57/61 GFN1-xTB: API (PCEM)                    OK       0.84 s 
58/61 GFN0-xTB: SP                            OK       0.42 s 
59/61 GFN0-xTB: API                           OK       0.80 s 
60/61 GFN0-xTB: SP  (PBC)                     OK       0.78 s 
61/61 GFN0-xTB: API (PBC)                     OK       0.78 s 

Ok:                   53
Expected Fail:         5
Fail:                  0
Unexpected Pass:       0
Skipped:               3
Timeout:               0
```

Note: is there any kind of "make install"? Because the executable is still called `xtb@exe`, and is still not located in a "bin" folder.

**Comment by awvwgk** [comment]
Just use
```bash
ninja -C build_intel install
```
You might want to adjust the `prefix` with `meson configure build_intel --prefix=/` and set the `DESTDIR` variable to something other than `/`, but this is up to you.

**Comment by pierre-24** [comment]
Thanks. Thus, it works :)

**Comment by awvwgk** [comment]
I will hold this PR back on purpose for now, because we are at a point where meson 0.49 is finally supported by some more mainstream package manages and I don't want to break this again for everybody. It was hard enough to introduce it in the first place :wink:.

But I will rebase it on the `master` from time to time so it can actually be used if really needed.

**Comment by pierre-24** [comment]
Do we really need functions of the 0.50 version?

**Comment by awvwgk** [comment]
Couldn't get it running without `link_language: 'fortran'`, which is a 0.51 feature of meson. If there is a workaround, which does not require to kick out all the C and C++ code from this repository I will immediately implement it.

**Comment by awvwgk** [comment]
@pierre-24 Both `stda` and `xtb4stda` use `make` based build systems, so the issue there is even more severe. I went away from `make` because the build-system gets pretty fast bloated if you add such options (checkout [the original build system of `xtb`](https://github.com/grimme-lab/xtb4stda/tree/master/MAKE) for example).

Patching up [my little addition to `xtb4stda`](https://github.com/grimme-lab/xtb4stda/blob/master/meson.build) shouldn't be to hard and since it is a pure Fortran project it can be done with meson 0.49 already.

**Comment by pierre-24** [comment]
... And I know from *internal* sources that stda is compilable without `-static`. 

Thus, I should be able to work my way through all of that, thanks! (now, I have to convince my system administrator that meson/ninja is not that hard to use, but that should be easy, since it really isn't).

**Pull request merged**
