### PR TITLE
Add build instructions with cygwin

### PR DESCRIPTION
**Pull request by njustcodingjs**
Add the way to get Cygwin-build xtb and upload the cygwin release.

### CODE REVIEW

**Comment by njustcodingjs** [comment]
I think this is a possible way to build xtb under Unix-like system. The '/STACK' parameter was used because I cannot use the command like 'ulimt -s unlimited' under the Windows system. I have to give enough stack to the program when I build it. In Unix-like system, if you have 'bash', this paramter is not necessary. 'xtb' can be built in the same way by using Cmake.

**Comment by awvwgk** [comment]
Okay, after some reading on cygwin things are getting clearer for me. Since you said all tests are passing, it is also able to handle Unix like file paths, which should remove the concern about Windows vs Unix path separators.

Therefore, I would ask you to move the cygwin section to the CMake guide (https://github.com/grimme-lab/xtb/blob/master/cmake/README.adoc), as the guide there is more suitable than the short overview in the main README.

Since you mentioned distribution, I would handle this similar to OSX, meaning there will be no binary release on GitHub, but we will aim for a conda-forge package.

**Comment by njustcodingjs** [comment]
OK, I will refork the repository. These days I tried to install a macos virtual machine on windows. If there is any progress, I will inform you in time.

**Comment by awvwgk** [comment]
Closed in favour of #296

**Pull request closed without merging**
