### PR TITLE
Update README.adoc

### PR DESCRIPTION
**Pull request by njustcodingjs**
Add the Cygwin-build xtb in README.adoc

### CODE REVIEW

**Comment by awvwgk** [comment]
Thanks, I currently trying to setup a cygwin build on appveyor (see https://ci.appveyor.com/project/awvwgk/xtb), but so far this is not really successful. Maybe I'm missing some packages, so it might be a good idea to have a list of required cygwin packages in the guide as well.

**Comment by njustcodingjs** [comment]
Yes, it seems to be lack of a blas library.

**Comment by njustcodingjs** [comment]
GNU compiler and math library should be added when installing cygwin. I will check the version this night.

**Comment by awvwgk** [comment]
Looks like I got the build working on the Appveyor server, both for CMake and meson, yet the testsuite is not running correctly and therefore the produced binary invalid. This is the list of cygwin packages used so far:

build | `--packages`
--- | ---
CMake | `python3-devel,gcc-fortran,cmake,make,liblapack-devel,liblapack,libopenblas`
meson | `python3-devel,gcc-fortran,meson,ninja,liblapack-devel,liblapack,libopenblas`

One thing I noticed, the build is just incredibly slow, taking 10 min with CMake/make and 7 min with meson/ninja and this is just the build not the actual testsuite. Seems like I can't really parallelize the build, which is not good.

**Pull request closed without merging**
