### PR TITLE
Fix some warnings

### LINKED ISSUE #1136: Undefined behavior in constrain_pot.f90
**Describe the bug**

GCC 14.1 says:
```
xtb/src/constrain_pot.f90:122:62:

  122 |                   dy = xyz(l,fix%atoms(i))-xyz(l,fix%atoms(j))
      |                                                              ^
Warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
xtb/src/constrain_pot.f90:121:21:

  121 |                do l = k+1, 3 !loop same-atom block-diagonal elements
      |                     ^
note: within this loop
```

**To Reproduce**

1. Load/Get GCC 14.1
2. `cmake -B_build -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_Fortran_COMPILER=gfortran -DCMAKE_BUILD_TYPE=Release`
3. `cd _build`
4. `make -j $(nproc)`

**Expected behaviour**

No warning.

**Additional context**

GCC 14.1 is used.
Release build is used.

### LINKED ISSUE #1137: Intent mismatch in frag_hess
**Describe the bug**

GCC 14.1 says:
```
xtb/src/gfnff/frag_hess.f90:483:19:

   43 |       subroutine eigsort4(lab,ew,u)
      |                         2
......
  483 | subroutine eigsort4(lab,u,ew)
      |                   1
Warning: INTENT mismatch in argument 'lab' between (1) and (2)
```

**To Reproduce**

1. Load/Get GCC 14.1
2. `cmake -B_build -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_Fortran_COMPILER=gfortran -DCMAKE_BUILD_TYPE=Release`
3. `cd _build`
4. `make -j $(nproc)`

**Expected behaviour**

No warning.

**Additional context**

GCC 14.1 is used.
Release build is used.

### LINKED ISSUE #1138: Rank mismatch in argument 'neighbours' in frag_hess.f90
**Describe the bug**

GCC 14.1 says:
```
xtb/src/gfnff/frag_hess.f90:413:0:

   24 |      function shortest_distance(nspin, start, goal, numnb, neighbours, input_distances, visited, precessor)
......
  413 | function shortest_distance(nspin, start, goal, numnb, neighbours, input_distances, visited, precessor)
Warning: Rank mismatch in argument 'neighbours' (2/3) between (1) and (2)
```

**To Reproduce**

1. Load/Get GCC 14.1
2. `cmake -B_build -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_Fortran_COMPILER=gfortran -DCMAKE_BUILD_TYPE=Release`
3. `cd _build`
4. `make -j $(nproc)`

**Expected behaviour**

No warning.

**Additional context**

GCC 14.1 is used.
Release build is used.

### PR DESCRIPTION
**Pull request by foxtran**
Closes #1136
Closes #1137
Closes #1138

I have reordered cycles in constrain_pot.f90 and optimize them a little bit.

In frag_hess.f90 the interfaces were written improperly. With this patch, it is fixed.

### CODE REVIEW

**Comment by foxtran** [comment]
I used data from #1073 to check that my changes did not break constrain_pot.f90. I used that input with the following builds:
1. GCC 14.1 + -DCMAKE_BUILD_TYPE=Debug (main branch)
2. GCC 14.1 + -DCMAKE_BUILD_TYPE=Release (main branch)
3. GCC 14.1 + -DCMAKE_BUILD_TYPE=Release (with patches)

Final geometries are:
1.
```
10
 energy: -17.791370056955 gnorm: 0.191183343954 xtb: 6.7.1 (88182d28a757ebc9ad4dd669307fb809b48a81c6)
C            0.08349250097352       -0.00000000000000       -1.66685150998999
O            0.08349250097352       -1.14450707899713       -2.06305817001501
O            0.08349250097352        1.06910911997901       -2.49832462899085
C            0.08349250097352        0.42305450598473       -0.20207950402105
H            0.96371475105800        1.05500486868295       -0.06821139357968
N            0.08349250097352       -0.66773800502435        0.75458303699029
H            0.90902648832390       -1.25411304946884        0.57262708314866
H           -0.74204156731040       -1.25411299922995        0.57262738718104
H           -0.79672982069372        1.05500478137452       -0.06821138570990
H            0.08349273134097       -0.34112066497356        1.72898418779322
```
2.
```
10
 energy: -17.791370056955 gnorm: 0.191183343950 xtb: 6.7.1 (88182d28a757ebc9ad4dd669307fb809b48a81c6)
C            0.08349250097352       -0.00000000000000       -1.66685150998999
O            0.08349250097352       -1.14450707899713       -2.06305817001501
O            0.08349250097352        1.06910911997901       -2.49832462899085
C            0.08349250097352        0.42305450598473       -0.20207950402105
H            0.96371475105773        1.05500486869461       -0.06821139357512
N            0.08349250097352       -0.66773800502435        0.75458303699029
H            0.90902648831421       -1.25411304940450        0.57262708325666
H           -0.74204156730071       -1.25411299916561        0.57262738728904
H           -0.79672982069344        1.05500478138618       -0.06821138570534
H            0.08349273134097       -0.34112066514917        1.72898418767818
```
3.
```
10
 energy: -17.791370056955 gnorm: 0.191183343958 xtb: 6.7.1 (88182d28a757ebc9ad4dd669307fb809b48a81c6)
C            0.08349250097352       -0.00000000000000       -1.66685150998999
O            0.08349250097352       -1.14450707899713       -2.06305817001501
O            0.08349250097352        1.06910911997901       -2.49832462899085
C            0.08349250097352        0.42305450598473       -0.20207950402105
H            0.96371475118518        1.05500486854107       -0.06821139345844
N            0.08349250097352       -0.66773800502435        0.75458303699029
H            0.90902648878815       -1.25411304908885        0.57262708380125
H           -0.74204156758555       -1.25411299899205        0.57262738761366
H           -0.79672982067103        1.05500478140184       -0.06821138548910
H            0.08349273128152       -0.34112066575391        1.72898418841631
```

Diff from 1. to 3.:
```diff
 10
- energy: -17.791370056955 gnorm: 0.191183343954 xtb: 6.7.1 (88182d28a757ebc9ad4dd669307fb809b48a81c6)
+ energy: -17.791370056955 gnorm: 0.191183343958 xtb: 6.7.1 (88182d28a757ebc9ad4dd669307fb809b48a81c6)
 C            0.08349250097352       -0.00000000000000       -1.66685150998999
 O            0.08349250097352       -1.14450707899713       -2.06305817001501
 O            0.08349250097352        1.06910911997901       -2.49832462899085
 C            0.08349250097352        0.42305450598473       -0.20207950402105
-H            0.96371475105800        1.05500486868295       -0.06821139357968
+H            0.96371475118518        1.05500486854107       -0.06821139345844
 N            0.08349250097352       -0.66773800502435        0.75458303699029
-H            0.90902648832390       -1.25411304946884        0.57262708314866
-H           -0.74204156731040       -1.25411299922995        0.57262738718104
-H           -0.79672982069372        1.05500478137452       -0.06821138570990
-H            0.08349273134097       -0.34112066497356        1.72898418779322
+H            0.90902648878815       -1.25411304908885        0.57262708380125
+H           -0.74204156758555       -1.25411299899205        0.57262738761366
+H           -0.79672982067103        1.05500478140184       -0.06821138548910
+H            0.08349273128152       -0.34112066575391        1.72898418841631
```

Diff from 1. to 2.:
```diff
10
- energy: -17.791370056955 gnorm: 0.191183343954 xtb: 6.7.1 (88182d28a757ebc9ad4dd669307fb809b48a81c6)
+ energy: -17.791370056955 gnorm: 0.191183343950 xtb: 6.7.1 (88182d28a757ebc9ad4dd669307fb809b48a81c6)
 C            0.08349250097352       -0.00000000000000       -1.66685150998999
 O            0.08349250097352       -1.14450707899713       -2.06305817001501
 O            0.08349250097352        1.06910911997901       -2.49832462899085
 C            0.08349250097352        0.42305450598473       -0.20207950402105
-H            0.96371475105800        1.05500486868295       -0.06821139357968
+H            0.96371475105773        1.05500486869461       -0.06821139357512
 N            0.08349250097352       -0.66773800502435        0.75458303699029
-H            0.90902648832390       -1.25411304946884        0.57262708314866
-H           -0.74204156731040       -1.25411299922995        0.57262738718104
-H           -0.79672982069372        1.05500478137452       -0.06821138570990
-H            0.08349273134097       -0.34112066497356        1.72898418779322
+H            0.90902648831421       -1.25411304940450        0.57262708325666
+H           -0.74204156730071       -1.25411299916561        0.57262738728904
+H           -0.79672982069344        1.05500478138618       -0.06821138570534
+H            0.08349273134097       -0.34112066514917        1.72898418767818
```

P.S. patch version is not changed since I'm not using git on testing machine

**Comment by foxtran** [comment]
The numerical difference comes from https://github.com/grimme-lab/xtb/pull/1139/commits/955ff888b5f80032d70099eaf3e0d349f811f087 but I do not see the reason...

**Comment by foxtran** [comment]
@awvwgk, is this difference OK? It looks like less than 10^-10 :-)

**Review by awvwgk — APPROVED** [review]
Looks good to me

**Pull request merged**
